# Auto-generated product image map. Regenerate: python generate_product_images.py
from __future__ import annotations

DEFAULT_PRODUCT_IMAGE = "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg"

CATEGORY_FALLBACK_IMAGES = {
    "Category A: Food": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Category B: Natural Cosmetics": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Category C: Spirituals": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Category D: Sara Nursery": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
}

PRODUCT_IMAGE_OVERRIDES = {
    "Aleovera gel": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Aleovera powder": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Almond Oil": "https://saraworldwide.com.np/wp-content/uploads/2020/10/aa.jpg",
    "Almond oil": "https://saraworldwide.com.np/wp-content/uploads/2020/10/aa.jpg",
    "Almonds": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Aloevera fresh juice": "https://saraworldwide.com.np/wp-content/uploads/2022/06/287329122_4928240767282481_4667855119876077382_n-1.jpg",
    "Aloeveraamala fresh juice": "https://saraworldwide.com.np/wp-content/uploads/2022/05/279123924_4804811382958754_2669167695708159299_n.jpg",
    "Amala Powder": "https://saraworldwide.com.np/wp-content/uploads/2019/01/amala-powder.jpg",
    "Amala fresh juice": "https://saraworldwide.com.np/wp-content/uploads/2022/06/aaa-scaled.jpg",
    "Amala whole": "https://saraworldwide.com.np/wp-content/uploads/2022/05/279123924_4804811382958754_2669167695708159299_n.jpg",
    "Amaranth Grain": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Apple Ber": "https://saraworldwide.com.np/wp-content/uploads/2018/10/apple-cider-new.jpg",
    "Apple cider vinegar": "https://saraworldwide.com.np/wp-content/uploads/2018/10/apple-cider-new.jpg",
    "Arjuna powder": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Arugula": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Ashwagandha": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Ashwagandha powder": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Asparagus": "https://saraworldwide.com.np/wp-content/uploads/2025/01/aw.jpg",
    "Asparagus powder": "https://saraworldwide.com.np/wp-content/uploads/2025/01/aw.jpg",
    "Bahedapowder": "https://saraworldwide.com.np/wp-content/uploads/2019/01/baheda-powder.jpg",
    "Barnyard Millet": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Basil": "https://saraworldwide.com.np/wp-content/uploads/2017/11/basil-seed-2-scaled.jpg",
    "Basil seed": "https://saraworldwide.com.np/wp-content/uploads/2017/11/basil-seed-2-scaled.jpg",
    "Basil seed oil": "https://saraworldwide.com.np/wp-content/uploads/2017/11/wf-scaled.jpg",
    "Beet root powder": "https://saraworldwide.com.np/wp-content/uploads/2019/11/beet-root-powder.jpg",
    "Beetroot": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Bell peppers": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Bhringraj Powder": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Black Rice": "https://saraworldwide.com.np/wp-content/uploads/2018/02/l-scaled.jpg",
    "Black Strap Molasses": "https://saraworldwide.com.np/wp-content/uploads/2018/05/m-w-scaled.jpg",
    "Black grapeseed oil": "https://saraworldwide.com.np/wp-content/uploads/2024/12/IMG_4006-1.jpeg-scaled.jpg",
    "Black seed oil": "https://saraworldwide.com.np/wp-content/uploads/2024/12/IMG_4006-1.jpeg-scaled.jpg",
    "Black turmeric": "https://saraworldwide.com.np/wp-content/uploads/2020/08/wild-turmeric-new...............jpg",
    "Body massage oil": "https://saraworldwide.com.np/wp-content/uploads/2025/12/516842583_10080655978707575_4751826126976610150_n-3-scaled.jpg",
    "Brahmi": "https://saraworldwide.com.np/wp-content/uploads/2019/09/brahami-powder.png",
    "Brahmi Powder": "https://saraworldwide.com.np/wp-content/uploads/2019/09/brahami-powder.png",
    "Broccoli": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Brown Rice": "https://saraworldwide.com.np/wp-content/uploads/2018/02/l-scaled.jpg",
    "Brown sugar": "https://saraworldwide.com.np/wp-content/uploads/2024/12/111.jpg",
    "Buckwheat": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "BudhaChitta": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Cabbage": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Camphor oil": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Carrot": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Carrots": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Cashew nuts": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Castorseed oil": "https://saraworldwide.com.np/wp-content/uploads/2018/02/cc-1-scaled.jpg",
    "Cauliflower": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Celery": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Chia": "https://saraworldwide.com.np/wp-content/uploads/2017/04/unnamed-1-scaled.jpg",
    "Chia seed": "https://saraworldwide.com.np/wp-content/uploads/2017/04/unnamed-1-scaled.jpg",
    "Chiaseed oil": "https://saraworldwide.com.np/wp-content/uploads/2019/01/chia-seed-oil.png",
    "Chirayata": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Cinnamon Stick": "https://saraworldwide.com.np/wp-content/uploads/2025/01/feb4b4c35973fd3e480c3d47e7adbc6a.jpg",
    "Clove oil": "https://saraworldwide.com.np/wp-content/uploads/2021/06/clove-oil.jpg",
    "Coconut Flakes": "https://saraworldwide.com.np/wp-content/uploads/2017/11/coconut-oil-latest.jpg",
    "Coconut Oil": "https://saraworldwide.com.np/wp-content/uploads/2017/11/coconut-oil-latest.jpg",
    "Coconut oil": "https://saraworldwide.com.np/wp-content/uploads/2022/06/IMG_7685-scaled.jpg",
    "Coins (God & Goddess)": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Cream": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Cucumber": "https://saraworldwide.com.np/wp-content/uploads/2020/11/126894153_2031243253677882_1631029915056568927_o.jpg",
    "Custard Apple": "https://saraworldwide.com.np/wp-content/uploads/2018/10/apple-cider-new.jpg",
    "Date Palm": "https://saraworldwide.com.np/wp-content/uploads/2017/11/sw-1.jpg",
    "Dehydrated Beans": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Beetroot": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Bell pepper": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Bitter Gourd": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Bottle Gourd": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Brussels sprouts": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Butternut Squash": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Cabbage": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Carrots": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Celery": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Corn": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Green beans": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Kale": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Mushrooms": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Onions": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Peas": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Potatoes": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Spinach": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Sweet potatoes": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dehydrated Tomatoes": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dilseed oil": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Dragon Fruit": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dried Apples": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dried Bananas": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dried Cranberries": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dried Kasmiri Garlic": "https://saraworldwide.com.np/wp-content/uploads/2024/08/image_123650291-copy.jpg",
    "Dried Kiwis": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dried Papayas": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dried Pears": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dried Pineapples": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Dried Wild Garlic": "https://saraworldwide.com.np/wp-content/uploads/2024/08/image_123650291-copy.jpg",
    "Dried blueberries": "https://saraworldwide.com.np/wp-content/uploads/2024/08/455729107_7855742024532326_2908406688006566351_n.jpg",
    "Fennel": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Fennelseed oil": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Fenugreek": "https://saraworldwide.com.np/wp-content/uploads/2020/11/wf.jpg",
    "Fenugreek Powder": "https://saraworldwide.com.np/wp-content/uploads/2020/11/wf.jpg",
    "Fenugreekseed oil": "https://saraworldwide.com.np/wp-content/uploads/2020/11/wf.jpg",
    "Figs": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Finger Millet": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Flax": "https://saraworldwide.com.np/wp-content/uploads/2024/12/f-web-scaled.jpg",
    "Flax seed": "https://saraworldwide.com.np/wp-content/uploads/2024/12/f-web-scaled.jpg",
    "Flaxseed oil": "https://saraworldwide.com.np/wp-content/uploads/2017/11/wf-scaled.jpg",
    "Foxtail Millet": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Gastric and piles relief": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Gems": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Giloy fresh juice": "https://saraworldwide.com.np/wp-content/uploads/2022/06/ggggg-scaled.jpg",
    "Giloya": "https://saraworldwide.com.np/wp-content/uploads/2022/06/ggggg-scaled.jpg",
    "Giloypowder": "https://saraworldwide.com.np/wp-content/uploads/2019/11/g.jpg",
    "Ginseng": "https://saraworldwide.com.np/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-02-at-5.09.07-PM-1.jpeg",
    "Good Sleep": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Green Cabbage": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Green Kale": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Guava": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Gucche Mushroom": "https://saraworldwide.com.np/wp-content/uploads/2024/06/sponge-mushroom-500x500-1.jpg",
    "Gymnema": "https://saraworldwide.com.np/wp-content/uploads/2017/11/GYMNEMA-SYLEBESTRE.jpg",
    "GymnemaSylvestre powder": "https://saraworldwide.com.np/wp-content/uploads/2017/11/GYMNEMA-SYLEBESTRE.jpg",
    "Hair growth oil": "https://saraworldwide.com.np/wp-content/uploads/2020/11/ow.jpg",
    "Harad powder": "https://saraworldwide.com.np/wp-content/uploads/2019/01/harad-powder.png",
    "Healthy drinks": "https://saraworldwide.com.np/wp-content/uploads/2021/08/hh-scaled.jpg",
    "Heart and diabetes care": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Hemp seed oil": "https://saraworldwide.com.np/wp-content/uploads/2018/11/hemp-seed-oil-1.jpg",
    "Henna Powder": "https://scontent-mxp1-1.xx.fbcdn.net/v/t39.30808-6/702604421_122217217298350145_8407654073845047177_n.jpg",
    "Henna powder": "https://scontent-mxp1-1.xx.fbcdn.net/v/t39.30808-6/702604421_122217217298350145_8407654073845047177_n.jpg",
    "Hibiscus": "https://saraworldwide.com.np/wp-content/uploads/2018/04/hibiscus.jpg",
    "Hibiscus Powder": "https://saraworldwide.com.np/wp-content/uploads/2018/04/hibiscus.jpg",
    "Hibiscus powder": "https://saraworldwide.com.np/wp-content/uploads/2018/04/hibiscus.jpg",
    "Honey": "https://saraworldwide.com.np/wp-content/uploads/2025/02/wh.jpg",
    "Indigo Powder": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Indigo powder": "https://saraworldwide.com.np/wp-content/uploads/2020/11/ow.jpg",
    "Insulin Plant": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Isabgol": "https://saraworldwide.com.np/wp-content/uploads/2017/11/IMG_7760-scaled.jpg",
    "Jaggery powder": "https://saraworldwide.com.np/wp-content/uploads/2021/06/42637b2e4763bf93e5b00ba6dfab132f.jpg",
    "Jamun Honey": "https://saraworldwide.com.np/wp-content/uploads/2024/06/moringa-honey.jpg",
    "Jamun Seed powder": "https://saraworldwide.com.np/wp-content/uploads/2019/03/DSC_0755.jpg",
    "Jamun cider vinegar": "https://saraworldwide.com.np/wp-content/uploads/2019/03/DSC_0755.jpg",
    "Jasmine": "https://saraworldwide.com.np/wp-content/uploads/2019/05/j-scaled.jpg",
    "Jasmine oil": "https://saraworldwide.com.np/wp-content/uploads/2021/07/Jasmin-Oil.png",
    "Jasmine water": "https://saraworldwide.com.np/wp-content/uploads/2019/05/j-scaled.jpg",
    "Jatamansi": "https://saraworldwide.com.np/wp-content/uploads/2019/02/Rose_Oil.png",
    "Jatamansi oil": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Jojoba": "https://saraworldwide.com.np/wp-content/uploads/2019/02/Rose_Oil.png",
    "Jojoba oil": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Jowar": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Kale": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Kewada water": "https://saraworldwide.com.np/wp-content/uploads/2019/05/kewada-water-photo-1.jpg",
    "Kodo Millet": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Lavender": "https://saraworldwide.com.np/wp-content/uploads/2019/02/Rose_Oil.png",
    "Lavender oil": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Lemon": "https://saraworldwide.com.np/wp-content/uploads/2021/07/Lemon-Grass.png",
    "Lemon grass oil": "https://saraworldwide.com.np/wp-content/uploads/2021/07/Lemon-Grass.png",
    "Licorice": "https://saraworldwide.com.np/wp-content/uploads/2018/02/l-scaled.jpg",
    "Licorice powder": "https://saraworldwide.com.np/wp-content/uploads/2018/02/l-scaled.jpg",
    "Litchi": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Little Millet": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Maca powder": "https://saraworldwide.com.np/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-02-at-5.09.05-PM.jpeg",
    "Mango": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Milk thistle": "https://saraworldwide.com.np/wp-content/uploads/2025/12/milk-thistle-final.jpg",
    "Milk thistle powder": "https://saraworldwide.com.np/wp-content/uploads/2017/05/mm.jpg",
    "Mint": "https://saraworldwide.com.np/wp-content/uploads/2017/11/mint.jpg",
    "Moringa": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Moringa Honey": "https://saraworldwide.com.np/wp-content/uploads/2024/06/moringa-honey.jpg",
    "Moringa Neem soap": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Moringa Plant": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Moringa powder": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Moringa seed oil": "https://saraworldwide.com.np/wp-content/uploads/2024/07/IMG_4021.jpeg-scaled.jpg",
    "MoringaMultaniMitti soap": "https://saraworldwide.com.np/wp-content/uploads/2021/03/aal-scaled.jpg",
    "Mosquito Repellent oil": "https://saraworldwide.com.np/wp-content/uploads/2025/12/516842583_10080655978707575_4751826126976610150_n-3-scaled.jpg",
    "Mucuna powder": "https://saraworldwide.com.np/wp-content/uploads/2018/05/DSC_0796.jpg",
    "MultaniMitti": "https://saraworldwide.com.np/wp-content/uploads/2018/11/mmm-scaled.jpg",
    "MultaniMutti powder": "https://saraworldwide.com.np/wp-content/uploads/2018/11/mmm-scaled.jpg",
    "Mushroom": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Musk": "https://saraworldwide.com.np/wp-content/uploads/2021/07/Jasmin-Oil.png",
    "Mustard": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Mustard oil": "https://saraworldwide.com.np/wp-content/uploads/2017/11/coconut-oil-latest.jpg",
    "Naked Barley": "https://saraworldwide.com.np/wp-content/uploads/2019/09/barley-grass.jpg",
    "Natural Astrilogy Gem Stone": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Natural Hair growth oil": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Neem": "https://saraworldwide.com.np/wp-content/uploads/2024/12/neem-oil-scaled.jpg",
    "Neem Plant": "https://saraworldwide.com.np/wp-content/uploads/2024/12/neem-oil-scaled.jpg",
    "Neem water": "https://saraworldwide.com.np/wp-content/uploads/2024/12/neem-oil-scaled.jpg",
    "Neemseed oil": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Noni fresh juice": "https://saraworldwide.com.np/wp-content/uploads/2022/06/no-scaled.jpg",
    "Oils": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Onion Oil": "https://saraworldwide.com.np/wp-content/uploads/2020/11/ow.jpg",
    "Onion seed oil": "https://saraworldwide.com.np/wp-content/uploads/2020/11/ow.jpg",
    "Orange peel oil": "https://saraworldwide.com.np/wp-content/uploads/2019/11/unnamed.jpg",
    "Orange peel powder": "https://saraworldwide.com.np/wp-content/uploads/2019/11/unnamed.jpg",
    "Oud": "https://saraworldwide.com.np/wp-content/uploads/2021/07/Jasmin-Oil.png",
    "Pain relief oil": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Papaya": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Pea Shoots": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Pearl Millet": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Peppermint oil": "https://saraworldwide.com.np/wp-content/uploads/2021/07/Lemon-Grass.png",
    "Pink Salt": "https://saraworldwide.com.np/wp-content/uploads/2019/01/pink-salt.jpg",
    "Pistachios": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Potatoes": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Proso Millet": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Protein powder": "https://saraworldwide.com.np/wp-content/uploads/2020/09/p-scaled.jpg",
    "Pumpkin seed": "https://saraworldwide.com.np/wp-content/uploads/2019/01/pp-scaled.jpg",
    "Pumpkin seed oil": "https://saraworldwide.com.np/wp-content/uploads/2019/01/pp-scaled.jpg",
    "Punarnava": "https://saraworldwide.com.np/wp-content/uploads/2017/05/Holy-Basil.jpg",
    "Quinoa seed": "https://saraworldwide.com.np/wp-content/uploads/2024/08/w-q-scaled.jpg",
    "Radish": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Raisins": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Red Mushroom": "https://saraworldwide.com.np/wp-content/uploads/2024/06/images-1.jpg",
    "Red Rice": "https://saraworldwide.com.np/wp-content/uploads/2018/02/l-scaled.jpg",
    "Religious Idols": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Rhita whole": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Ritha Powder": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Ritha powder": "https://saraworldwide.com.np/wp-content/uploads/2019/01/harad-powder.png",
    "Rose": "https://saraworldwide.com.np/wp-content/uploads/2019/02/Rose_Oil.png",
    "Rose oil": "https://saraworldwide.com.np/wp-content/uploads/2019/02/Rose_Oil.png",
    "Rose water": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Rosemary": "https://saraworldwide.com.np/wp-content/uploads/2021/07/Jasmin-Oil.png",
    "Rosemary oil": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Rudraksha": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Sandal": "https://saraworldwide.com.np/wp-content/uploads/2021/06/IMG_7629-scaled.jpg",
    "Sandal Powder": "https://saraworldwide.com.np/wp-content/uploads/2019/04/sandal-wood-powder.jpg",
    "Sandal powder": "https://saraworldwide.com.np/wp-content/uploads/2019/04/sandal-wood-powder.jpg",
    "Sandal water": "https://saraworldwide.com.np/wp-content/uploads/2021/06/IMG_7629-scaled.jpg",
    "Saw palmetto powder": "https://saraworldwide.com.np/wp-content/uploads/2017/11/sw-1.jpg",
    "Senna powder": "https://saraworldwide.com.np/wp-content/uploads/2019/11/seee-scaled.jpg",
    "Serpentine": "https://saraworldwide.com.np/wp-content/uploads/2017/04/fina.jpg",
    "Sesameseed oil": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Shaligram": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Shankhapushpi": "https://saraworldwide.com.np/wp-content/uploads/2017/05/Holy-Basil.jpg",
    "Shikakai Powder": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Shikakai powder": "https://saraworldwide.com.np/wp-content/uploads/2019/01/harad-powder.png",
    "Shikakai whole": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Shilajit": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Shivalinga": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Sindur Plant": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Sphatik": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Spinach": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Spirulina": "https://saraworldwide.com.np/wp-content/uploads/2017/04/index.jpg",
    "Spirulina powder": "https://saraworldwide.com.np/wp-content/uploads/2017/04/index.jpg",
    "Spray": "https://saraworldwide.com.np/wp-content/uploads/2019/05/rose.jpg",
    "Stevia powder": "https://saraworldwide.com.np/wp-content/uploads/2017/11/stock-photo-dry-stevia-leaf-in-the-basket-with-wooden-spoon-on-an-old-wooden-floor-1488828680.jpg",
    "Stones": "https://saraworldwide.com.np/wp-content/uploads/2024/06/shw.jpg",
    "Sugar control": "https://saraworldwide.com.np/wp-content/uploads/2024/12/111.jpg",
    "Sunflower": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Sunflower seed": "https://saraworldwide.com.np/wp-content/uploads/2017/04/unnamed-1-scaled.jpg",
    "Sweet Potatoes": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Swiss Chard": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Taichin Rice": "https://saraworldwide.com.np/wp-content/uploads/2018/02/l-scaled.jpg",
    "Tea Tree oil": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Thyme": "https://saraworldwide.com.np/wp-content/uploads/2020/09/IMG_8078-scaled.jpg",
    "Thyme seed oil": "https://saraworldwide.com.np/wp-content/uploads/2020/09/IMG_8078-scaled.jpg",
    "Timmur oil": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Tomatoes": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Triphalapowder": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Tulsi": "https://saraworldwide.com.np/wp-content/uploads/2017/05/Holy-Basil.jpg",
    "Turmeric": "https://saraworldwide.com.np/wp-content/uploads/2020/08/wild-turmeric-new...............jpg",
    "Turmeric powder": "https://saraworldwide.com.np/wp-content/uploads/2020/08/wild-turmeric-new...............jpg",
    "Vetiver water": "https://saraworldwide.com.np/wp-content/uploads/2019/05/IMG_7632-scaled.jpg",
    "Walnut Oil": "https://saraworldwide.com.np/wp-content/uploads/2020/10/walm-scaled.jpg",
    "Walnut oil": "https://saraworldwide.com.np/wp-content/uploads/2020/10/walm-scaled.jpg",
    "Walnuts": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Watermelon seed": "https://saraworldwide.com.np/wp-content/uploads/2020/11/IMG_8158.jpg",
    "Wild Honey": "https://saraworldwide.com.np/wp-content/uploads/2025/02/wh.jpg",
    "Wild turmeric": "https://saraworldwide.com.np/wp-content/uploads/2020/08/wild-turmeric-new...............jpg",
    "Yarsagumba": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
    "Yellow Squash": "https://saraworldwide.com.np/wp-content/uploads/2024/08/moringa.jpg",
}


def resolve_product_image_url(product_name: str, category_name: str, subcategory_name: str = "") -> str:
    if product_name in PRODUCT_IMAGE_OVERRIDES:
        return PRODUCT_IMAGE_OVERRIDES[product_name]
    return CATEGORY_FALLBACK_IMAGES.get(category_name, DEFAULT_PRODUCT_IMAGE)
